### PR TITLE
minor spelling mistake

### PR DESCRIPTION
**Pull request by prenagha**

### CODE REVIEW

**Comment by jzdziarski** [comment]
thanks!

**Comment by prenagha** [comment]
any interest in patches related to default rules for built in apps like
`allow prefix "$HOME/Library/Safari/" "/Applications/Safari.app/Contents/MacOS/Safari"`
or did you want to keep it minimal?

**Comment by jzdziarski** [comment]
i've thought about it, and recently added whitelisting of cache, saved state, and container folders to keep the noise to a minimum, but for now probably keeping everything else fair game for the user control

**Comment by prenagha** [comment]
sounds good. initial first-time load is of course a (very necessary) beating. tricky to find the right balance. I guess anyone using this won't mind, and will probably like seeing (almost) everything.

**Pull request merged**
